site_name: SARVe Wiki
site_url: https://AI-Driven-HEP.github.io/SARVe/
repo_url: https://github.com/AI-Driven-HEP/SARVe/
repo_name: AI-Driven-HEP/SARVe
theme:
  name: material

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - content.action.edit

  icon:
    logo: material/server
    repo: simple/github

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.footer

extra:
  social:
    - icon: simple/github
      link: https://github.com/AI-Driven-HEP



markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
